### ISSUE TITLE
[Feature] Run in DBT Cloud

### ISSUE THREAD

**Issue by calleo** [godatadriven/pytest-dbt-core#21]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Lots of my colleagues uses the DBT Cloud IDE. It lowers the entry barrier for anyone not experience with IDEs, git, etc. With that in mind, I would like them to also have the possibility to write unit tests and run the tests in that environment.

### Describe alternatives you've considered

Running tests in CI pipeline, but this creates a very slow feedback loop.

### Who will this benefit?

Any DBT developer using DBT Cloud IDE

### Are you interested in contributing this feature?

Yes

### Anything else?

I have now clue if this is even remotely possible. Does that DBT cloud runtime include Pytest? Is it possible to create a DBT package which pulls in additional packages from pypi?

**Comment by JCZuurmond** [comment]
Hi @calleo, sorry that I missed your issue! I changed my notification settings so that this won't happen again.

I am afraid that we can not run this package in the dbt cloud. The dbt cloud blocks you from running anything other than `dbt`. This is on purpose, I guess they want to avoid misuse of the dbt cloud and for security reasons.
